### PR TITLE
FUSE-7065 perfcounterreporter no longer runs on Windows 7

### PR DESCRIPTION
**Pull request by BitBuster**

### CODE REVIEW

**Comment by tedoc2000** [comment]
Does this mean we won't get the synthetic counter on Windows 7.. If so then can we somehow?

**Comment by beccatortell** [comment]
I believe this is a fix for a bug that I reported yesterday entitled "perfcounterreporter no longer runs on Windows 7". See https://signalfuse.atlassian.net/browse/FUSE-7065

**Comment by BitBuster** [comment]
It should work on windows 7 but I can not verify it.

**Comment by BitBuster** [comment]
Thanks.

**Comment by mpetazzoni** [comment]
Hey folks,

Avoid referencing JIRA issues on public repositories, as those aren't reachable to non-SignalFx employees. Bugs and issues with public code should be reported, discussed, and dealt with entirely here on GitHub.

Thanks!

**Pull request merged**
